from __future__ import annotations

from typing import List, Tuple

import numpy as np

from algorithms.nmf.nnls import NNLSOptions, nnls


def _normalize_columns(X: np.ndarray, norm: str = "l2") -> np.ndarray:
    if norm == "l2":
        d = np.linalg.norm(X, axis=0, keepdims=True) + 1e-16
        return X / d
    if norm == "l1":
        d = np.sum(np.abs(X), axis=0, keepdims=True) + 1e-16
        return X / d
    return X


def _orth_proj_residual(X: np.ndarray, K: List[int]) -> np.ndarray:
    if len(K) == 0:
        return X.copy()
    W = X[:, K]
    # Orthogonal projector onto span(W)
    Q, _ = np.linalg.qr(W, mode="reduced")
    return X - Q @ (Q.T @ X)


def spa(X: np.ndarray, r: int, *, normalize: str = "l2") -> List[int]:
    """
    Successive Projection Algorithm (SPA).
    Returns indices K of selected columns.
    """
    Xn = _normalize_columns(X, normalize)
    K: List[int] = []
    R = Xn.copy()
    for _ in range(r):
        norms = np.sum(R * R, axis=0)
        k = int(np.argmax(norms))
        if k in K:
            # fallback if duplicate
            norms[k] = -np.inf
            k = int(np.argmax(norms))
        K.append(k)
        R = _orth_proj_residual(Xn, K)
    return K


def snpa(X: np.ndarray, r: int, *, normalize: str = "l2") -> List[int]:
    """
    Simplified SNPA variant: choose columns by maximizing residual after nonnegative projection.
    """
    Xn = _normalize_columns(X, normalize)
    K: List[int] = []
    R = Xn.copy()
    for _ in range(r):
        norms = np.sum(R * R, axis=0)
        k = int(np.argmax(norms))
        if k in K:
            norms[k] = -np.inf
            k = int(np.argmax(norms))
        K.append(k)
        # Project onto cone generated by current anchors via NNLS
        if len(K) < r:
            W = Xn[:, K]
            H, _, _ = nnls(W, Xn, NNLSOptions(algo="HALS", inneriter=300, delta=1e-6))
            R = np.maximum(0.0, Xn - W @ H)
    return K


def vca(X: np.ndarray, r: int, *, normalize: str = "l2", random_state: int = 0) -> List[int]:
    """
    Very light VCA-like selection using random directional projections.
    """
    Xn = _normalize_columns(X, normalize)
    rng = np.random.default_rng(random_state)
    K: List[int] = []
    for _ in range(r):
        d = rng.standard_normal(Xn.shape[0])
        y = d / (np.linalg.norm(d) + 1e-16)
        k = int(np.argmax(y @ Xn))
        if k in K:
            # fallback: use SPA step
            rest = [i for i in range(Xn.shape[1]) if i not in K]
            k = int(rest[np.argmax(np.sum((Xn[:, rest]) ** 2, axis=0))])
        K.append(k)
    return K


def faw(X: np.ndarray, r: int, *, normalize: str = "l1") -> List[int]:
    """
    Simple FAW-style selection by maximizing distinctiveness after l1 normalization.
    """
    Xn = _normalize_columns(X, normalize)
    K: List[int] = []
    scores = np.sum(np.abs(Xn), axis=0)
    for _ in range(r):
        k = int(np.argmax(scores))
        if k in K:
            scores[k] = -np.inf
            k = int(np.argmax(scores))
        K.append(k)
        # Reduce scores for columns similar to the chosen anchor
        sim = Xn[:, k].T @ Xn
        scores = scores - np.maximum(sim, 0.0)
    return K


def solve_h_given_indices(X: np.ndarray, K: List[int]) -> Tuple[np.ndarray, np.ndarray]:
    """
    Given selected indices K, solve H >= 0 minimizing ||X - X[:,K] H||_F.
    Returns (W, H) with W = X[:,K].
    """
    W = X[:, K]
    H, _, _ = nnls(W, X, NNLSOptions(algo="HALS", inneriter=1000, delta=1e-6))
    return W, H

